apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: spider-app
  labels:
    app: spider
    target: pneumonia
  name: get-pneumonia
spec:
  replicas: 0
  selector:
    labels:
      app: spider
      target: pneumonia
  template:
    metadata:
      labels:
        app: spider
        target: pneumonia
    spec:
      containers:
      - image: 192.168.11.3:10000/ci/
        name: get-pneumonia-spider
        imagePullPolicy: IfNotPresent