apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spider-app
  labels:
    app: spider
    target: pneumonia
  name: get-pneumonia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spider
      target: pneumonia
  template:
    metadata:
      labels:
        app: spider
        target: pneumonia
    spec:
      containers:
      - image: 192.168.11.3:10000/ci/get_pneumonia:latest.
        name: get-pneumonia-spider
        imagePullPolicy: IfNotPresent